"""Add financial intelligence columns to merchant mapping

Revision ID: 3c683ae8d68f
Revises: 8e786b8ebcbb
Create Date: 2026-07-07 10:54:32.646091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3c683ae8d68f'
down_revision: Union[str, None] = '8e786b8ebcbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchant_mapping', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('merchant_mapping', sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('merchant_mapping', sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('merchant_mapping', sa.Column('times_seen', sa.Integer(), nullable=False))
    op.add_column('merchant_mapping', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    op.add_column('merchant_mapping', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchant_mapping', 'reason')
    op.drop_column('merchant_mapping', 'last_seen')
    op.drop_column('merchant_mapping', 'times_seen')
    op.drop_column('merchant_mapping', 'aliases')
    op.drop_column('merchant_mapping', 'confidence')
    op.drop_column('merchant_mapping', 'subcategory')
    # ### end Alembic commands ###
