"""rename clerk_id to auth_id

Revision ID: 8e786b8ebcbb
Revises: a652bf9fe494
Create Date: 2026-07-04 16:07:33.939073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8e786b8ebcbb'
down_revision: Union[str, None] = 'a652bf9fe494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_id', sa.String(), nullable=False))
    op.drop_constraint('users_clerk_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['auth_id'])
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_clerk_id_key', 'users', ['clerk_id'])
    op.drop_column('users', 'auth_id')
    # ### end Alembic commands ###
