"""Change transaction confidence to integer

Revision ID: bd4b5494ff07
Revises: cbb7fea20642
Create Date: 2026-07-07 11:45:36.543597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd4b5494ff07'
down_revision: Union[str, None] = 'cbb7fea20642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'ai_confidence',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'ai_confidence',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
