"""Change confidence to integer

Revision ID: cbb7fea20642
Revises: 3c683ae8d68f
Create Date: 2026-07-07 11:31:48.103719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cbb7fea20642'
down_revision: Union[str, None] = '3c683ae8d68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_mapping', 'confidence',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchant_mapping', 'confidence',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=4, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
