"""multi_statement_manual_feed

Revision ID: d278ee078ab6
Revises: bd4b5494ff07
Create Date: 2026-07-10 10:42:24.127668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd278ee078ab6'
down_revision: Union[str, None] = 'bd4b5494ff07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_no', sa.String(), nullable=True),
    sa.Column('ifsc', sa.String(), nullable=True),
    sa.Column('account_type', sa.Enum('savings', 'current', 'cash', 'wallet', name='account_type_enum'), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manual_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=True),
    sa.Column('merchant_id', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('category_source', sa.String(), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant_mapping.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('statements', sa.Column('source_file_hash', sa.String(), nullable=True))
    op.add_column('statements', sa.Column('account_id', sa.String(), nullable=True))
    op.add_column('statements', sa.Column('continuity_warning', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'statements', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')
    
    op.execute("""
    CREATE VIEW transactions_view AS
    SELECT 
        t.id, 
        t.user_id, 
        s.account_id AS account_id, 
        t.date AS txn_date, 
        t.description, 
        t.amount, 
        t.type AS direction, 
        t.currency,
        t.balance,
        t.category_id, 
        t.merchant_id, 
        t.merchant_name, 
        t.subcategory, 
        t.tags, 
        t.notes, 
        'bank' AS source,
        t.category_source,
        t.ai_confidence,
        t.created_at,
        t.updated_at
    FROM transactions t
    LEFT JOIN statements s ON t.statement_id = s.id

    UNION ALL

    SELECT 
        mt.id, 
        mt.user_id, 
        mt.account_id, 
        mt.txn_date, 
        mt.description, 
        mt.amount, 
        mt.direction, 
        mt.currency,
        NULL AS balance,
        mt.category_id, 
        mt.merchant_id, 
        mt.merchant_name, 
        mt.subcategory, 
        mt.tags, 
        mt.notes, 
        'manual' AS source,
        mt.category_source,
        mt.ai_confidence,
        mt.created_at,
        mt.updated_at
    FROM manual_transactions mt;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS transactions_view;")
    op.drop_constraint(None, 'statements', type_='foreignkey')
    op.drop_column('statements', 'continuity_warning')
    op.drop_column('statements', 'account_id')
    op.drop_column('statements', 'source_file_hash')
    op.drop_table('manual_transactions')
    op.drop_table('accounts')
    # ### end Alembic commands ###
